name: Docker Image CI Frontend

on:
  push: 
    branches: [ "main" ]
    tags:
      - 'v*'  # support git tag pushes
    paths:
      - 'shop-online-app/frontend/**'
  pull_request:
    paths:
      - 'shop-online-app/frontend/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # âœ… Extract version if tag exists (and reuse it later)
      - name: Extract version from Git tag
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      # âœ… Echo tag version if this is a tag push
      - name: Echo version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run:  | 
          echo "ğŸ¯ Building test image for version: $VERSION"

      # âœ… Build image for tag only (without push)
      - name: Build Docker image for tag (no push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./shop-online-app/frontend/Dockerfile
          push: false
          load: true
          tags: react-fronted:${{ env.VERSION }}

      # ğŸ” Scan vulnerabilities before push to production
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0 
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:latest  

      # ğŸš€ Build and push image when pushing/merging to main
      - name: Build and push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          file: ./shop-online-app/frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:${{ env.VERSION || github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:latest
