name: Docker Image CI Frontend

on:
  push:
    branches: [ "main" ]  # ğŸ” ×›×©×¢×•×©×™× push ×œ-main
    tags:                 # ğŸ·ï¸ ×›×©×¢×•×©×™× git tag (×›××• v1.0.0)
      - 'v*'
    paths:
      - 'shop-online-app/frontend/**'
  pull_request:
    paths:
      - 'shop-online-app/frontend/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # âœ… ×”×’×“×¨×ª IMAGE_TAG ×œ×¤×™ tag ××• fallback ×œ-run_id
      - name: ğŸ”¢ Set IMAGE_TAG from Git tag or fallback
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            echo "ğŸ¯ VERSION=$VERSION"
            echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV
          else
            echo "ğŸªª Fallback to run ID"
            echo "IMAGE_TAG=${GITHUB_RUN_ID}" >> $GITHUB_ENV
          fi

      - name: ğŸ§¾ Print final image tag
        run: |
          echo  "ğŸ“¦ Image will be tagged as: ${{ env.IMAGE_TAG }}"

      - name: ğŸ§± Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./shop-online-app/frontend/Dockerfile
          push: false
          load: true
          tags: react-fronted:${{ env.IMAGE_TAG }}

      - name: ğŸ” Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0 
        with:
          image-ref: react-fronted:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: 0
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: ğŸš€ Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./shop-online-app/frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:latest
