name: Docker Image CI Frontend

on:
  push:
    branches:
      - "main"
    paths:
      - 'shop-online-app/frontend/**'

  create:
    tags:
      - 'v*'

  pull_request:
    paths:
      - 'shop-online-app/frontend/**'


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ”¢ Extract version from Git tag
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: ğŸ§ª Echo version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "ğŸ¯ Git tag detected: $VERSION"

      - name: ğŸ§± Build Docker image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: . # root of the repo
          file: ./shop-online-app/frontend/Dockerfile
          push: false # don't push yet
          load: true  # required for Trivy to scan local image
          tags: react-fronted:${{ env.VERSION || github.run_id }}

      - name: ğŸ§¾ Print built image name + tag
        run: |
          TAG="${{ env.VERSION }}"
          if [ -z "$TAG" ]; then
            TAG="${{ github.run_id }}"
          fi
          echo "ğŸ“¦ Built image: ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:$TAG"

      - name: ğŸ” Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0 
        with:
          image-ref: react-fronted:${{ env.VERSION || github.run_id }}  # scan local image
          format: 'table'               # format output
          exit-code: 0                  # â† donâ€™t fail the build on critical issues
          ignore-unfixed: true          # â† ignore unfixed vulnerabilities
          severity: 'CRITICAL'          # only show critical issues

      - name: ğŸš€ Build and push to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: . 
          file: ./shop-online-app/frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:${{ env.VERSION || github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/react-fronted:latest
